version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-net
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - '5050:80'
      depends_on:
        - postgres
      networks:
        - postgres-net
  app:
    build: .
    container_name: application
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    command: ["node", "dist/main.js"]
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    networks:
      - postgres-net

volumes:
  pgdata:

networks:
  postgres-net:

  
